// 
// Decompiled by Procyon v0.5.36
// 

package org.dom4j.io;

class SAXModifyException extends RuntimeException
{
    protected SAXModifyException(final Throwable cause) {
        super(cause);
    }
}
